chores:
  - url: "https://github.com/markormesher/tedium-testing"
    directory: "chores/fast-no-op"
  - url: "https://github.com/markormesher/tedium-testing"
    directory: "chores/slow-no-op"
  - url: "https://github.com/markormesher/tedium-testing"
    directory: "chores/always-change-single-file"
  - url: "https://github.com/markormesher/tedium-testing"
    directory: "chores/always-change-unique-file"
